#!/usr/bin/env python3
"""dgm_proposal_demo.py — first synthetic D-G self-modification proposal (Phase 1 #6).

Generates one MergeProposal end-to-end, runs it through the merge gate,
prints the MergeDecision, and writes both to data-snapshots/dgm-YYYY-MM-DD.json
for the capstone audit log.

The point of this script is to *exercise* the gate, not to actually modify
production code. Three synthetic proposals are generated by default:

1. APPROVE-worthy: Brier improves by 0.012 on n=45 held-out; human_approved=True
2. BLOCK_NO_BRIER_GAIN: Brier improves only by 0.002 (below 0.005 threshold)
3. BLOCK_NO_HUMAN_APPROVAL: Brier improves 0.020 but human_approved=False

After running, the audit JSON shows exactly which proposals would have
merged under the discipline. This is the first artifact for the capstone
thesis defending the claim that the D-G search space is *intentionally
constrained* by Brier-improvement + HITL gates.

Run manually:
    python3 scripts/dgm_proposal_demo.py
"""
from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import sys

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
sys.path.insert(0, str(REPO / "src"))

from calibration.self_modification import (
    MergeProposal,
    evaluate as merge_evaluate,
)


def synthetic_proposals() -> list[MergeProposal]:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return [
        MergeProposal(
            proposal_id=f"{today}-prompt-tighten-macro-voice",
            kind="prompt_edit",
            description="Tighten Macro voice rationale to ≤120 chars (was ≤140); "
                        "Reflexion cluster shows 30% of dissents truncated mid-thought.",
            baseline_brier=0.182,
            candidate_brier=0.170,
            held_out_n=45,
            human_approved=True,
        ),
        MergeProposal(
            proposal_id=f"{today}-indicator-atr-floor-2pct",
            kind="indicator_threshold",
            description="Raise ATR stop floor from 1.5%×ATR to 2%×ATR on names with realized "
                        "vol > 35%. Backtest shows narrow improvement on Brier; consider weight.",
            baseline_brier=0.182,
            candidate_brier=0.180,
            held_out_n=45,
            human_approved=True,
        ),
        MergeProposal(
            proposal_id=f"{today}-voice-roster-add-quant-momentum",
            kind="voice_roster",
            description="Add 6th voice: Quant Momentum (12-1 month price momentum, "
                        "Asness 1997). Brier improves but Alex not ready to ship.",
            baseline_brier=0.182,
            candidate_brier=0.162,
            held_out_n=45,
            human_approved=False,
        ),
    ]


def main() -> int:
    proposals = synthetic_proposals()
    out_rows: list[dict[str, Any]] = []
    print(f"[dgm] evaluating {len(proposals)} synthetic proposals against merge gate")
    for p in proposals:
        decision = merge_evaluate(p)
        print(f"[dgm] {p.proposal_id} ({p.kind}) → {decision.status.value}: {decision.reason}")
        out_rows.append({
            "proposal": asdict(p),
            "decision": {
                "status": decision.status.value,
                "proposal_id": decision.proposal_id,
                "brier_delta": decision.brier_delta,
                "reason": decision.reason,
            },
        })

    payload = {
        "status": "ok",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "n_proposals": len(proposals),
        "proposals": out_rows,
    }

    out_path = REPO / "data-snapshots" / f"dgm-{datetime.now(timezone.utc).strftime('%Y-%m-%d')}.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2))

    approved = sum(1 for r in out_rows if r["decision"]["status"] == "approve")
    print(f"[dgm] {approved}/{len(proposals)} proposals approved by gate")
    print(f"[dgm] wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
