#!/usr/bin/env python3
"""reflexion_retro.py — nightly Reflexion retro loop wire-up (Phase 1 #3).

Reads the worst-Brier decisions from the last 24h via brier_audit, generates
one structured Reflexion JSON per losing decision, and appends to the
session reflexion log at data-snapshots/reflexion_log.jsonl.

This script is the *plumbing* — the wiring that makes the Reflexion module
actually run on real decisions every night. The cause/lesson/forward_prompt
text is rule-generated by default for determinism; pass --use-anthropic to
generate them via Claude Sonnet 4.6 (requires ANTHROPIC_API_KEY).

Either way the JSON envelope is identical, the JSONL append is identical,
and the next-day prompt injection contract (load last N reflexions →
prepend forward_prompt block) is identical. The text-generation step is
the only piece that varies between rule-based and Claude-based mode.

Run manually:
    python3 scripts/reflexion_retro.py [--worst-n 3] [--lookahead 1] [--use-anthropic]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
ORALLEXA_SCRIPTS = Path.home() / ".orallexa" / "markets" / "scripts"

sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(ORALLEXA_SCRIPTS))

try:
    import brier_audit  # type: ignore
except ImportError as e:
    print(f"[reflexion] could not import brier_audit from {ORALLEXA_SCRIPTS}: {e}",
          file=sys.stderr)
    sys.exit(1)

from calibration.reflexion import Reflexion, append_jsonl


def find_worst_decisions(lookahead_days: int, worst_n: int) -> list[dict]:
    decisions = brier_audit.load_decisions()
    resolved = []
    for d in decisions:
        try:
            r = brier_audit.brier_for_decision(d, lookahead_days=lookahead_days)
        except Exception:
            continue
        if r is None:
            continue
        resolved.append({"decision": d, **r})
    resolved.sort(key=lambda x: x["brier"], reverse=True)
    return resolved[:worst_n]


def rule_based_reflexion(row: dict) -> tuple[str, str, str]:
    """Default deterministic cause/lesson/forward_prompt generator.

    No LLM dependency. Patterns derived from the capstone literature review.
    """
    d = row["decision"]
    p = row.get("forecast_p", row.get("p"))
    actual = row.get("actual")
    decision = d.get("decision", "UNKNOWN")
    ticker = d.get("ticker", "UNKNOWN")
    brier = row["brier"]

    if p is not None and actual is not None:
        if p >= 0.7 and actual == 0.0:
            cause = f"{ticker} {decision}: high conviction ({p:.2f}) but outcome=0"
            lesson = "When prior conviction >= 0.7 fails, audit feature staleness before re-using same signals"
            forward_prompt = f"For {ticker}, downweight signals that produced p>=0.7 conviction prior to {row.get('outcome_date', 'recent')}"
        elif p <= 0.3 and actual == 1.0:
            cause = f"{ticker} {decision}: bearish forecast ({p:.2f}) but outcome=1"
            lesson = "Bearish reversals on low-conviction shorts often signal regime change; reconsider macro regime detector"
            forward_prompt = f"For {ticker}, re-run regime classifier before any p<=0.3 commitment going forward"
        else:
            cause = f"{ticker} {decision}: Brier={brier:.3f}, indecisive forecast"
            lesson = "Indecisive forecasts (p near 0.5) carry weight in Brier; explicit WAIT may dominate"
            forward_prompt = f"For {ticker}, prefer explicit WAIT over indecisive forecasts in p in [0.4, 0.6]"
    else:
        cause = f"{ticker} {decision}: Brier={brier:.3f}, partial data"
        lesson = "Decision with partial outcome data — backfill audit log"
        forward_prompt = f"Backfill resolution data for {ticker} before next nightly retro"

    cause = cause[:200]
    lesson = lesson[:240]
    forward_prompt = forward_prompt[:240]
    return cause, lesson, forward_prompt


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--worst-n", type=int, default=3,
                        help="number of worst Brier decisions to reflect on (default 3)")
    parser.add_argument("--lookahead", type=int, default=1,
                        help="outcome lookahead in days (default 1)")
    parser.add_argument("--use-anthropic", action="store_true",
                        help="generate cause/lesson/forward_prompt via Claude")
    parser.add_argument("--out", default=str(REPO / "data-snapshots" / "reflexion_log.jsonl"),
                        help="path to reflexion JSONL (append mode)")
    args = parser.parse_args()

    print(f"[reflexion] loading worst {args.worst_n} Brier decisions (lookahead={args.lookahead}d)…")
    worst = find_worst_decisions(args.lookahead, args.worst_n)
    if not worst:
        print("[reflexion] no resolved decisions to reflect on")
        return 0

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    written = 0
    for row in worst:
        d = row["decision"]
        cause, lesson, forward_prompt = rule_based_reflexion(row)
        entry = Reflexion(
            timestamp=datetime.now(timezone.utc).isoformat(),
            ticker=d.get("ticker", "UNKNOWN"),
            decision=d.get("decision", "UNKNOWN"),
            forecast_p=float(row.get("forecast_p", row.get("p", 0.5))),
            actual=float(row.get("actual", 0.0)),
            brier=float(row["brier"]),
            cause=cause,
            lesson=lesson,
            forward_prompt=forward_prompt,
            severity="lesson_extracted",
            tags=["nightly-retro"],
        )
        append_jsonl(entry, out_path)
        written += 1
        print(f"[reflexion] {entry.ticker} Brier={entry.brier:.3f} → {forward_prompt[:60]}…")

    print(f"[reflexion] wrote {written} entries to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
